bump_version: null
lint: {multiqc_config: false}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Jin Yan Khoo
  description: Extract methylation calls from long reads
  force: true
  is_nfcore: true
  name: methylong
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - multiqc
  version: 1.0.0dev
update: null
bump-versions:
  modkit/pileup: '0.4.2'