bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Jin Yan Khoo
  description: Extract methylation calls from long reads
  force: true
  is_nfcore: true
  name: methylong
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
